# Numpy Assignment

In [1]:
# 1. What is a Python library? Why do we use Python libraries?
'''
Library : Collection of function, which can be reusable and optimised the program.

A Python library is a collection of code and functions that can extend the capabilities of the Python programming language.
They can help developers work on tasks without having to reinvent the wheel.

Reduce work: Libraries can reduce the amount of work that needs to be done from scratch. For example, you can use Seaborn to generate 
visualizations with a single line of code.

Save time and effort: Libraries can be integrated into projects to save time and effort.

Reduce the need to write new code: Libraries can help developers avoid having to write new code every time they run the same process.

Improve efficiency: Libraries can make everyday tasks more efficient.

'''



In [3]:
# 2. What is the difference between Numpy array and List?
'''
Numpy Array : Array is basic unit of numpy and it is container to store data and array is statistically defined not dynamic.
Array store Homogineous Data and array is faster than List.

List :List store Hetrogenious Data, List are not stored themselves, it stores address of the element. List used refrencing, refrencing all the element.

'''
import numpy as np
List = [1, 2, 3.4, 5, "Rajat", True]
print(List)
arr = np.array([1, 2, 3.4, 5, "Rajat", True]) # All data are converted into string(Homogineous)
print(arr)


[1, 2, 3.4, 5, 'Rajat', True]
['1' '2' '3.4' '5' 'Rajat' 'True']


In [4]:
# 3. Find the shape, size and dimension of the following array?

# [[1, 2, 3, 4]
# [5, 6, 7, 8],
# [9, 10, 11, 12]]

import numpy as np
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
arr = np.array(arr)
print(f"Shape : {arr.shape}")
print(f"Size : {arr.size}")
print(f"Dimension : {arr.ndim}")


Shape : (3, 4)
Size : 12
Dimension : 2


In [5]:
# 4. Write python code to access the first row of the following array?
'''
[[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
print(f"First Row : {arr[0]}")


First Row : [1, 2, 3, 4]


In [6]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
'''
[[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
print(f"Third Row and Fourth column element is: {arr[3-1][4-1]}")


Third Row and Fourth column element is: 12


In [7]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
'''
[[1, 2, 3, 4]
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
for i in range(0, len(arr), 2):
    for j in range(0, len(arr[0]), 2):
        print(arr[i][j])


1
3
9
11


In [8]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

import numpy as np
arr = np.random.randint(0, 2, size = (3, 3))
print(arr)

[[1 0 1]
 [1 1 1]
 [0 0 1]]


In [15]:
# 8. Describe the difference between np.random.rand and np.random.randn?
'''
The main difference between np.random.rand and np.random.randn is the distribution of the random values they generate. np.random.rand generates
values from a uniform distribution (in the range [0,1)), while np.random.randn generates values from a normal distribution.

'''

print(np.random.rand(2, 3)) # this will gives uniform distribution value.
print()

print(np.random.randn(2, 3)) # this will gives normal distribution value.
print()

print(np.random.rand(1)) 
print()

print(np.random.randn(1))

[[0.40007906 0.59767191 0.5688863 ]
 [0.50812426 0.22877061 0.32382955]]

[[1.42845715 0.37340247 0.4097706 ]
 [0.3106961  1.91960195 0.36322865]]

[0.94141763]

[0.42320809]


In [22]:
# 9. Write code to increase the dimension of the following array?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
arr = np.array(arr)
print(f"Initial Dimension : {arr.ndim}")
arr = arr.reshape(1, 1, 1, 1, 1, 1, 3, 4)
print(arr)
print(f"Final Dimension : {arr.ndim}")

Initial Dimension : 2
[[[[[[[[ 1  2  3  4]
       [ 5  6  7  8]
       [ 9 10 11 12]]]]]]]]
Final Dimension : 8


In [23]:
# 10. How to transpose the following array in NumPy?
'''
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]
'''
arr = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
arr = np.array(arr)
print(arr.T)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [24]:
# 11. Consider the following matrix:

# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

# Perform the following operation using Python1
# 1. index wise multiplication
# 2. Matrix Mutiplication
# 3. add both matrix
# 4. subtract B from A
# 5. Divide matrix B by A
import numpy as np

matrixA = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

matrixB = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]

matrixA = np.array(matrixA)
matrixB = np.array(matrixB)

# 1. index wise multiplication
indexwise_Multiplication = matrixA*matrixB
print(f"Index wise Multiplication : {indexwise_Multiplication}")

# 2. Matrix Mutiplication
matrix_Multiplication = matrixA @ matrixB.T
print(f"Matrix Multiplication : {matrix_Multiplication}")

# 3. add both matrix
add_Matrices = matrixA + matrixB
print(f"Addition of two matrices : {add_Matrices}")

# 4. subtract B from A
Subtract = matrixB - matrixA
print(f"subtract B from A : {Subtract}")

# 5. Divide matrix B by A
Divide = matrixB/matrixA
print(f"Divide matrix B by A : {Divide}")

Index wise Multiplication : [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication : [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition of two matrices : [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
subtract B from A : [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Divide matrix B by A : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
# 12.  Which function in Numpy can be used to swap the byte order of an array?

'''
In numpy byteswap() function can be used to swap the byte order of an array. this function return a new array with byte order swapped.
'''
import numpy as np
arr = [1, 2, 3, 4, 5, 6]
arr = np.array(arr)
arr_swap = arr.byteswap()
print(f"Original Array : {arr}")
print(f"Swapped Array : {arr_swap}")



Original Array : [1 2 3 4 5 6]
Swapped Array : [ 72057594037927936 144115188075855872 216172782113783808
 288230376151711744 360287970189639680 432345564227567616]


In [8]:
# 13.  What is the significance of the np.linalg.inv function?
'''
The np.linalg.inv() function is used to calculate the inverse of a matrix. The inverse of a matrix is that matrix which when multiplied with 
the original matrix, results in an identity matrix.

'''
matrixA = [[1, 2, 3],
       [6, 6, 2],
       [9, 0, 11]]
matrixA = np.array(matrixA)
matrixA_inv = np.linalg.inv(matrixA)
print(f"Original Matrix : {matrixA}")
print(f"Inverse Matrix : {matrixA_inv}")


Original Matrix : [[ 1  2  3]
 [ 6  6  2]
 [ 9  0 11]]
Inverse Matrix : [[-0.34375     0.11458333  0.07291667]
 [ 0.25        0.08333333 -0.08333333]
 [ 0.28125    -0.09375     0.03125   ]]


In [13]:
# 14. What does the np.reshape function do, and how is it used?
'''
np.reshape function is used to change the shape of the matrix without changing the matrix size and it's data. The new shape must be compatible
with the old one, though an index of -1 can be used to infer one dimension. Initial array size are not change or changes will not reflected
original array(shallow copy).
np.reshape function commonly used in multiplication of matrix in machine learning model.
'''
import numpy as np
matrixA = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
matrixA = np.array(matrixA)
print(matrixA.reshape(2, 6))
print()
print(matrixA.reshape(1, -1))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [24]:
# 15. What is broadcasting in Numpy?
'''
Broadcasting is a powerful feature of NumPy that allows you to perform arithmetic operations on arrays of different shapes. When you try to
perform an operation on two arrays of different shapes, NumPy will automatically broadcast the smaller array to the shape of the larger array.
This allows you to perform element-wise operations on arrays of different shapes without having to reshape them.
'''
import numpy as np
arr = np.zeros((3,4))
print(arr)
arr = arr + 5
print()
print(arr)

arr = arr*3
print()
print(arr)

a = np.array([1, 2, 3, 4])
arr = arr + a
print()
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]

[[15. 15. 15. 15.]
 [15. 15. 15. 15.]
 [15. 15. 15. 15.]]

[[16. 17. 18. 19.]
 [16. 17. 18. 19.]
 [16. 17. 18. 19.]]
